### ISSUE TITLE
Dockerimage

### ISSUE THREAD

**Issue by Its4Nik** [dstein64/neuralart#1]
Hey there I have written a Dockerimage with flask to request images from the "API". 
Should i open a PR? Or don't you want that functionality

**Comment by dstein64** [comment]
Hi @Its4Nik, a Docker image with a flask server for accessing neuralart is beyond the scope for the project. If you open source the work (e.g., in a separate repository) and share the link in this Issue, I'd be interested to check it out and others might find it helpful.
